name: Daily Affirmation Sender

on:
  schedule:
    - cron: "*/5 * * * *"   # 09:00 s√°ng VN (UTC+7)
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Function
        run: |
          curl -X POST "YOUR_FUNCTION_URL"
